using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using DG.Tweening;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class GameManager : MonoBehaviour
{
    // НЬБлХц РЮНКХЯНК
    public static GameManager Instance { get; private set; }

    private void Awake()
    {
        Instance = this;
    }


    public Fade fade;

    [SerializeField]
    List<EventBase> eventBases = new List<EventBase>();
    bool gameEnd = false;

    [SerializeField]
    EventBase currentBase = null;

    // 0Йј ЦЉХфИЎОѓ 1~12 РЬКЅЦЎ 
    [SerializeField]
    private int _currentEventnum = 0;
    public int currentEventNum { get { return _currentEventnum; } private set { _currentEventnum = value;  } }

    public int priousChoiceNumber = 0;

    //ЕЗ
    public float Money = 1000000;

    public string HappyEndingSceneName = "";
    public string BadEndingSceneName = "";

    // ПЙ: АдРг УЪБтШ­
    private void Start()
    {
        Setup();
    }

    private void Update()
    {
        if(currentBase != null)
        {
            currentBase.Execute(this);
        }
    }

    [ContextMenu("NextEvent")]
    public void NextEvent()
    {
        if (gameEnd)
            return;


        StartCoroutine(eNextEvent());


    }

    public IEnumerator eNextEvent()
    {

        _currentEventnum++;
        UIManager.Instance.AllUIOff();
        print($"--------{_currentEventnum} NextEvent--------");


        


        if (currentEventNum > eventBases.Count)
        {
            //
            EndGame();
            gameEnd = true;
            yield return null;
        }
        else if(currentEventNum == 1)
        {
            // ЦЉХфИЎОѓ

            if (currentBase != null)
                currentBase.Exit(this);

            // fade БтДйИЎБт
            yield return new WaitForSeconds(fade.fadeTime + 1f + 0.1f);

            currentBase = eventBases[_currentEventnum];
            currentBase.Enter(this);

            
        }
        else
        {

            if (currentBase != null)
                currentBase.Exit(this);

            // fade БтДйИЎБт
            yield return new WaitForSeconds(fade.fadeTime + 1f + 0.1f);

            currentBase = eventBases[_currentEventnum];
            currentBase.Enter(this);


        }


        print($"-------------------------------");


        yield return null;


    }

    void Setup()
    {
        // РЬКЅЦЎ КЃРЬНК ИЎНКЦЎ МТОї

        for(int i = 0; i < this.transform.childCount; i++)
        {
            EventBase _base = this.transform.GetChild(i).GetComponent<EventBase>();


            if(_base != null)
            {
                eventBases.Add(_base);

            }
            else
            {
                print($"{this.transform.GetChild(i).name} ПЁ EventBaseАЁ ОјРН");
            }
        }

        currentBase = eventBases[0];
        currentBase.Enter(this);

    }

    IEnumerator EndGame()
    {
        // fade
        print("EndАдРг ШЃУт ЕЪ");

        yield return StartCoroutine(fade.eTutoFadeOut());

        if(Money > 10000000f)
        {
            SceneManager.LoadScene(HappyEndingSceneName);
        }
        else
        {
            SceneManager.LoadScene(BadEndingSceneName);
        }

    }


    public void RecordPreviousChoice(int num)
    {
        priousChoiceNumber = num;
    }



}
